name: Github Actions validator
description: Validate the Github Actions workflows

inputs:
  actionlint-version:
    description: Version of actionlint to use
    default: 1.6.27

runs:
  using: "composite"
  steps:
    - name: Install actionlint
      uses: asdf-vm/actions/install@v3
      with:
        tool_versions: |
          actionlint ${{ inputs.actionlint-version }}

    - name: Run actionlint and format output as JSON
      id: actionlint
      shell: bash
      run: actionlint -format '{{json .}}' | tee actionlint_output.json

    - name: Set status
      shell: bash
      run: |
        if [ -s actionlint_output.json ]; then
          exit 1
        fi

    - name: Generate comment
      if: success() || failure()
      shell: python
      run: |
        import json

        with open("actionlint_output.json") as fd:
            data = json.load(fd)

        errors_by_file = {}
        for error in data:
            errors_by_file.setdefault(error["filepath"], []).append(error)

        comment = ""
        for file, errors in errors_by_file.items():
            file_comment_lines = [f"<details><summary><code>{file}</code></summary>"]
            for error in errors:
                url = f"https://github.com/${{ github.repository }}/blob/${{ github.sha }}/{file}#L{error['line']}"
                snippet_lines = ["<pre>", *error["snippet"].split("\n"), "</pre>"]
                file_comment_lines.extend([
                    error["message"],
                    f"<a href={url}>View in file</a>",
                    "\n".join(snippet_lines),
                    "<hr />"
                ])
            file_comment_lines.append("</details>")
            comment += "<br />".join(file_comment_lines)

        with open("comment.md", "w") as fd:
            fd.write("## :warning: Github Actions validator failed\n\n")
            fd.write(comment)

    - name: Post results in PR (failure)
      if: failure()
      uses: thollander/actions-comment-pull-request@v2
      with:
        filePath: comment.md
        comment_tag: actions-validator

    - name: Post results in PR (success)
      if: success()
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: "## :white_check_mark: Github Actions validator passed"
        comment_tag: actions-validator