name: Pull Request

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  actions-validator:
    name: Run Github Actions validator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Github Actions workflows
        uses: philips-software/github-actions-linter@armand/backport-changes
